### ISSUE TITLE
UnitLoggerFactory formatting problems with JSON messages

### ISSUE THREAD

**Issue by paulio** [Cysharp/ZLogger#152]
I'm using ZLogger in Unity and it appears there isn't the same formatting configuration options as the non-Unity version? But I use the default configuration logging JSON causes exceptions that appear to be because of the Format(message, args) processing. E.g. a JSON message containing { } is considered as the Format expression and it attempts to process the expression and either doesn't log the expected output or simply throws an exception. Is there a way to change this behaviour or use our own custom formatter?

**Comment by hadashiA** [comment]
@paulio Would you share your problematic configuration?

If you want to log JSON, `UseJsonFormatter` is available.

```cs
var loggerFactory = LoggerFactory.Create(logging =>)
{
    logging.AddZLoggerUnityDebug(options => { 
    {
        options.UseJsonFormatter(formatter => { /* setup json... */ })
    }); 
});
````

**Comment by paulio** [comment]
For clarity, I don't want all the log output to be in a JSON format, I want messages that contain JSON to be correctly logged. E.g. 
INFO | {"field":value}

**Comment by paulio** [comment]
Additional example;
`var message = "The server returned {"field":12}"; logger.LogDebug(message, stacktrace, logType);`

**Comment by hadashiA** [comment]
> logger.LogDebug(message, stacktrace, logType);

Perhaps there is a misunderstanding in the usage.

The first argument is a "message template" defined by Microsoft.Extensions.
The subsequent arguments are variables of the "message template".
https://learn.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line

When using ILogger, you do not need to pass logType and stacktrace. (You can't)

And ZLogger provides ZLogDebug instead of LogDebug. See the Microsoft.Extensions.DependencyInjection documentation and the ZLogger documentation.
