### ISSUE TITLE
NuGet Clone failure in Unity With dotnet 4.8.1

### ISSUE THREAD

**Issue by Reag** [Cysharp/ZLogger#153]
Currently, if you follow the install instructions for Unity (2022.3.x) project set to .Net Standard 2.1, it will function as expected.

However, if you have the project set to .Net Framework, the ZLogger NuGet is configured to deliver an incorrect version of the Microsoft.Bcl.AsyncInterfaces. This leads to a compile error, as the ZLoggerUnityDebugLoggerProvider cannot compile, as the interface IAsyncDisposable is in both Microsoft.Bcl.AsyncInterfaces and mscorlib (System).

There is a work around, setting your project temporarily to .Net Standard 2.1 then doing the NuGet Restore, but this will cause huge problems in automated pipelines

**Comment by neuecc** [comment]
Thank you. Due to the somewhat special of Unity's .NET Framework and .NET Standard 2.1, there can be inconsistencies with definitions on NuGet.  
Does this issue with NuGetForUnity match what you're referring to?  
https://github.com/GlitchEnzo/NuGetForUnity/issues/621
Please give a +1(and comment) to this, or it might be necessary to open a new issue.

**Comment by Reag** [comment]
That appears to be the cause, yes
