### ISSUE TITLE
Unity 2021.2 link issues

### ISSUE THREAD

**Issue by drew-512** [Cysharp/ZLogger#52]
Hi @neuecc, thank you for all your hard work and I tell people about Zlogger whenever I can!

However, it would be great to secure Unity 2021.2 compatibility as it seems there are multiple linking issues unfortunately.  We are switching to 2021.2 and will need to drop Zlogger if we can't resolve this. 

So first, one removes the 4 libs now in Unity to clear errors:
```
Microsoft.Bcl.AsyncInterfaces
System.Buffers
System.Memory
System.Threading.Tasks.Extensions
```

However, then these two errors appear:
```
Assets/Scripts/ZLogger/Unity/UnityLoggerFactory.cs(40,33): error CS0012: The type 'IAsyncDisposable' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

Assets/Scripts/ZLogger/Unity/UnityLoggerFactory.cs(41,24): error CS0012: The type 'IAsyncDisposable' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

Also, there are dozens of these warnings:
```
Assets/Scripts/ZLogger/Entries/FormatLogEntry.cs(22,32): warning CS0436: The type 'AllowNullAttribute' in 'ZLogger/Shims/NullableAttributes.cs' conflicts with the imported type 'AllowNullAttribute' in 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Using the type defined in 'ZLogger/Shims/NullableAttributes.cs'.
```

Perhaps you could do a distro/release intended for 2021.2?  Please let us know how we can support, friend.

**Comment by noname77** [comment]
Subscribing, same on 2022 beta.

I can add that since I need to work in multiple Unity environments, instead of removing the mentioned .dlls, I added define constraints to all 4 as pictured below:
![image](https://user-images.githubusercontent.com/5903414/147111926-1403b69b-b199-4cb0-a926-0028e5f27e20.png)

However, this does not solve the errors so I'm also curious how this can be solved

Best
Wiktor

**Comment by noname77** [comment]
@drew-512 I wanted to report back that i managed to get ZLogger to work with Unity 2021 today with a hint from [this](https://forum.unity.com/threads/unity-future-net-development-status.1092205/page-6#post-7466417) unity forum post.

In particulear:
 - I switched back to .NET Standard 2.1 (from my previous .NET Framework configuration), though not sure if this is necessary
 - I added `!UNITY_2021` define constraint to all current dlls supplied with ZLogger
 - I re-downloaded all packages from nuget (in version 6.0.0) and extracted the 2.0 (2.1 where available) versions of the .dlls. Also added `UNITY_2021` define constraint to those
 - I also had to add System.Diagnostics.DiagnosticSource.dll. Might be due to going from `.NET Framework -> .NET Standard`, i didn't readd this for pre 2021 dlls yet
 
Some steps might not be necessary. It got it working for me, though i only tested in the editor so far.

For reference, i keep the .dlls in `Plugins/Cysharp/ZLogger/Plugins` and i attached my updated contents of `Plugins/Cysharp` for anyone interested.

[Cysharp.zip](https://github.com/Cysharp/ZLogger/files/7770293/Cysharp.zip)

Best,
Wiktor

**Comment by drew-512** [comment]
Awesome @noname77 thank you so much.  Looks like things are safe for now and that is safe to assume things will get better as Unity make key decisions. 

Hopefully down the road we can expect more 2021.2 friendly releases but I get that for now the priority is accommodating 2020.X.  Until then, thanks again and lmk how we can support ZLogger.
