### ISSUE TITLE
Double clicking the log line in the console doesn't open the file from which the log was initiated

### ISSUE THREAD

**Issue by igor84** [Cysharp/ZLogger#62]
Instead it opens ZLoggerExtensions file. The only way I know to solve this is to distribute ZString and ZLogger as precompiled DLLs since Unity will then open the first file that is not from DLL.

**Comment by hadashiA** [comment]
Thanks for the suggestion.
So we considered that Unity's `[HideInCallstack]` attribute, but decided not to support it because of the following:

- ZLogger does not seem to be able to cleanup the stack trace completely because it goes through lambda expressions, etc.
- HideInCallstack] is needed even for Unity-independent parts, but the source code seems to be a bit complicated.
- It may not be complete because the behavior depends on the Console window settings.
